export const workPageFilterList = [
  { display: 'all', path: 'all' },
  { display: 'social media design', path: 'social-media-design' },
  { display: 'display ads', path: 'display-ads' },
  { display: 'websites', path: 'websites' },
  { display: 'logos', path: 'logos' },
  { display: 'Illustrations', path: 'Illustrations' },
  { display: 'print', path: 'print' },
  { display: 'infographics', path: 'infographics' },
  { display: 'icons', path: 'icons' },
  { display: 'video editing', path: 'video-editing' },
  { display: 'brand guides', path: 'brand-guides' },
  { display: 'presentations', path: 'presentations' },
  { display: 'motion graphics', path: 'motion-graphics' },
  { display: 'landing pages', path: 'landing-pages' },
  { display: 'stationary sets', path: 'stationary-sets' },
];
